### PR TITLE
Add generation of an interface for each separate API; improve generated README.md

### PR DESCRIPTION
**Pull request by tjquinno**
Generate an interface for each API (as well as the already-generated concrete class which now implements the generated interface). The interface helps clarify the contract the generated library exposes to developers.

Updated the generated `README.md` to explain what files are generated and how to use them, with some Helidon WebClient specific information.

### CODE REVIEW

**Review by tvallin — COMMENTED** [review]
What do you think about adding unit tests for generated API implementation code ?

**Comment by tjquinno** [comment]
Adding unit and functional tests is definitely on the to-do list. I want to stabilize what is being generated before I write the tests.

**Review by tvallin — APPROVED** [review]

**Comment by tjquinno** [comment]
Marked as a draft because I will submit a more complete one soon.

**Comment by tjquinno** [comment]
Closing as superseded by #51

**Pull request closed without merging**
